services:
  modified:
    image: semtech/mu-javascript-template:latest
    restart: 'no'
    labels:
      - 'logging=true'
    environment:
      - NODE_ENV=development
      - NO_BABEL_NODE=true
      - CLEANUP_DUPLICATES_CRON=0 * * * * # Every hour
      - CLEANUP_DUPLICATES_AT_START=true
    ports:
      - '8083:80'
      - '9224:9229'
    volumes:
      - ../app-lokaal-mandatenbeheer/config/modified:/config
      - ./:/app
    networks:
      - debug
networks:
  debug:
    external: true
